name: Telegram Notification Push
on:
  push
  
jobs:

  telegram:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: send message on push
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: markdown
        message: |
           **Push Notify**
           ${{ github.actor }} created commit ${{ github.sha }}:
           Commit message: ${{ github.event.commits[0].message }}
           
           Repository: ${{ github.repository }}
           
           ref: ${{ github.ref }}
           See changes: [click me](${{ github.event.commits[0].url }})