name: Telegram Notification Push
on:
  push
  
jobs:

    telegram-notify:
        runs-on: ubuntu-latest
        steps:
            - name: String Process
              id: sp
              run: | 
                echo "repo=$(echo "${{ github.repository }}" | sed -r 's/([][>~+{}|\.\*-])/\\\1/g')" >> $GITHUB_OUTPUT
                echo "commit_msg=$(echo ${{ github.event.head_commit.message }} | sed -r 's/([][>~+{}|\.\*-])/\\\1/g')" >> $GITHUB_OUTPUT
            - name: send message on push
              uses: Juuroku/telegram-messaging@master
              with:
                telegram-token:  ${{ secrets.TELEGRAM_TOKEN }}
                telegram-chat: ${{ secrets.TELEGRAM_ID }}
                message: |
                    *[${{ steps.sp.outputs.repo }}](${{ github.server_url }}/${{ github.repository }}) Push Event*
                    REF: ${{ github.ref_name }}
                    [LATEST COMMIT](${{ github.event.head_commit.url }}): 
                        ${{ steps.sp.outputs.commit_msg }}
                        
                parse: 'markdown'