name: Telegram Notification Push
on:
  push
  
jobs:

  bulid:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: send message on push
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
           ${{ github.actor }} created commit ${{ github.sha }}:
           Commit message: ${{ github.event.commits[0].message }}
           
           Repository: ${{ github.repository }}
           
           See changes: ${{ github.event.commits[0].url }}
           
           ${{ toJSON(github.event) }}