name: Telegram Notification Release
on:
  release
  
jobs:

  bulid:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: send message on release
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
           # ${{ github.event.name }}
           ${{ github.actor }} created Release ${{ github.release }}:
           
           Repository: ${{ github.release.repo }}
           Path: ${{ github.event.path }}