name: Telegram Notification Release
on:
  release
  
jobs:

  telegram:
    name: telegram-notify
    runs-on: ubuntu-latest
    steps:
    - name: send message on release
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: markdown
        message: |
           **Release Notify**
           ${{ github.actor }} created Release ${{ github.ref }}:
           
           See note : [${{ github.repository }}](https://github.com/${{ github.repository }}/releases/tag/${{ github.ref }})