name: Telegram Notification Release
on:
  release
  
jobs:

  release-notify:
    runs-on: ubuntu-latest
    name: send message by telegram bot
    steps:
        - name: Release Notification
          uses: Juuroku/telegram-messaging@master
          with:
            telegram-token:  ${{ secrets.TELEGRAM_TOKEN }}
            telegram-chat: ${{ secrets.TELEGRAM_ID }}
            message: |
               **Release Notify**
               ${{ github.actor }} created Release ${{ github.ref }}:
               
               See note : [${{ github.repository }}](https://github.com/${{ github.repository }}/releases/tag/${{ github.ref }})
            parse: 'markdown'